### ISSUE TITLE
The nompi version is likely fragile... if not broken... after 8.2.0

### ISSUE THREAD

**Issue by mahf708** [conda-forge/esmf-feedstock#101]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

We should stop packaging the nompi version because it will likely fail for certain capabilities. This is likely caused by the decision to add ParallelIO. Will submit a PR to fix, and add a test for something like `ESMF_RegridWeightGen` which seems to work only when paired with an MPI.

### Installed packages

```shell
na
```

### Environment info

```shell
na
```

**Comment by xylar** [comment]
We may want to mark `nompi` builds as broken for >8.2.0 for this reason.  There may be some cases what are useful but in `ESMF_RegridWeightGen` is proving to be broken and confusing to debug in `nompi` builds as soon as ParallelIO was required, as @mahf708 points out.

**Comment by MuellerSeb** [comment]
So is the plan to remove the `nompi` version or to fix it? I'd prefer the second option.

**Comment by MuellerSeb** [comment]
Ah I see. The new `mpi_serial` is the way to go. Does this work the same way as the `nompi` version then?

**Comment by xylar** [comment]
@mahf708, can you verify that this is fixed for the latest 8.4.2 `nompi` builds?  I think it is and we can maybe close this.  I don't think we want to mark the previous `nompi` builds as broken because that typically causes more harm than good.
