### ISSUE TITLE
ESMF app installation does not respect install prefix on Darwin

### ISSUE THREAD

**Issue by bekozi** [conda-forge/esmf-feedstock#13]
Use `install_name_tool` in build script until fix is available in a tagged ESMF version.

**Comment by ocefpaf** [comment]
Thanks for digging into this @bekozi. Are you preparing a PR or should I do it?

**Comment by ocefpaf** [comment]
Oops. Just saw the self-assign :smile:

**Comment by bekozi** [comment]
> Oops. Just saw the self-assign

This. :wink: 

This fix will look something like:

```
ESMF_LIB_PATH=${PREFIX}/lib/libesmf.dylib
APPS=( ESMF_Info ESMF_RegridWeightGen ESMF_Regrid ESMF_Scrip2Unstruct )
for APP in "${APPS[@]}"; do
    ESMF_APP_PATH=${PREFIX}/bin/${APP}
    install_name_tool -change ${ESMF_ORIGINAL_LIB_PATH} ${ESMF_LIB_PATH} ${ESMF_APP_PATH}
done
```
