### ISSUE TITLE
Development builds?

### ISSUE THREAD

**Issue by bekozi** [conda-forge/esmf-feedstock#15]
@ocefpaf Is it possible to create feedstocks for pre-release software (i.e. development branches, HEAD)? We would like to reuse the CI infrastructure in `conda-forge` for building `esmf` HEAD as a number of users need bleeding edge code and would like to use conda. Is there a policy for this?

**Comment by ocefpaf** [comment]
@bekozi we are working on this as this is quite a common request. (Yours is the second today BTW :wink:)

So far we only did that (manually) for `matplotlib`, but the discussion is to provide an automated way and some guidelines on how to do it.

**Comment by bekozi** [comment]
Thanks. Is this discussion taking place somewhere? I'd be interested in seeing how it develops.

**Comment by ocefpaf** [comment]
Yep. Here: https://github.com/conda-forge/conda-forge.github.io/issues/147

**Comment by bekozi** [comment]
Much appreciated! :bow:

**Comment by ocefpaf** [comment]
Let's leave this open until we have a mechanism in place. (Helps me keep track of things.)

**Comment by ocefpaf** [comment]
@bekozi I forgot about this issue! I'll create a branch for the dev releases and you can send PR to that branch. The binaries will be published in the `dev` label channel though. People will be able to install it with the command:

```shell
conda create --name TEST --channel conda-forge/label/dev esmf
```

**Comment by ocefpaf** [comment]
You can send the dev releases PR to https://github.com/conda-forge/esmf-feedstock/tree/dev
