### ISSUE TITLE
Return "make check" to build script

### ISSUE THREAD

**Issue by bekozi** [conda-forge/esmf-feedstock#22]
Travis-CI times out with parallel tests. Increasing the wall time will obviously address this. Sounds like the great leaders are developing plan to procure more capacity allowing the full suite of ESMF tests to run: https://github.com/conda-forge/conda-forge.github.io/issues/306.

`make check` should be returned to the build script once wall times are fungible.

**Comment by xylar** [comment]
Is this still an issue, now that builds are with Azure?
