### ISSUE TITLE
Build from tags not from git

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/esmf-feedstock#28]
Would it be possible to build from tags and not from git?

**Comment by bekozi** [comment]
Yes, once Sourceforge is stable. Git is the most reliable now and these builds have been waiting for too long. Once it is stable we'll switch from Git.

**Comment by bekozi** [comment]
@CJ-Wright Do you have admin privileges on anaconda.org? I think it is best to delete the `v7.1.0r` packages for ESMF and ESMPy there until the SF issues are resolved, or we find a workaround. Sorry for the trouble, and thanks in advance.

https://anaconda.org/conda-forge/esmf/files
https://anaconda.org/conda-forge/esmpy/files

**Comment by bekozi** [comment]
Scratch that. We have a workaround URL. I'll leave this open until we migrate back to tags.

**Comment by xylar** [comment]
@bekozi, any progress on this?
