### ISSUE TITLE
version numbering for ESMF (e.g. 7.1.0r) causes problems with conda 4.6.*

### ISSUE THREAD

**Issue by xylar** [conda-forge/esmf-feedstock#35]
An attempt to install `esmf` with the latest `conda` and a spec with a wildcard such as:
```
conda create -n test_esmf "esmf>=7.1.*"
```
or 
```
conda create -n test_esmf "esmf>=7.1"
```
leads to an error like:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - esmf[version='>=7.1.*']
```

The issue seems to be the non-standard `r` at the end of the version number.  Conda uses [PEP 440](https://www.python.org/dev/peps/pep-0440) to parse the syntax of version numbers, and the trailing `r` doesn't fit into that parsing.

This issue could potentially be fixed in `conda` and I'm willing to look into it.  But I wondered if it would be feasible to just drop the non-standard `r` or in some other way make the `esmf` package compatible with the version numbering expected by `conda`.

See https://github.com/conda/conda/issues/8158 and https://github.com/conda/conda/issues/8309

**Comment by xylar** [comment]
@ocefpaf, since you have a good birds-eye view of conda and conda-forge, I'm wondering if you have thoughts on how you'd like to see this odd case resolved.

**Comment by ocefpaf** [comment]
I prefer that we drop the the `r` in the version. It is better to be `PEP 440` compliant. I'm looking into it...
