### ISSUE TITLE
Fortran?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/esmf-feedstock#5]
Looks like we are `yum` installing Fortran. Is there a good reason not to just the `gcc` package here? The problem is that as is there will be a missing `libgfortran` dependency in some cases. Is it possible for us to switch over to using the `gcc` package here?

**Comment by ocefpaf** [comment]
> Is there a good reason not to just the `gcc` package here?

No reason. I fixed a few oh these some time ago but this one slipped under the radar. Thanks for bringing it up!

**Comment by jakirkham** [comment]
No worries. I have auditing all the feedstocks using `gcc`.

We now have devtoolset-2 gcc included in the Docker image (recently tested to make sure it is working). So, basically everyone building on Linux should drop the `gcc` package if they are just doing C++0x or C++11 builds with it. Fortran and OpenMP still should use the package though. There are issues across all existing feedstocks for this now.

This was just a false positive for that use case. Though it still deserves attention, but for a different reason. 😄
