### ISSUE TITLE
build 0 of 8.1.0.beta.snapshot.33 (6 packages) on main

### ISSUE THREAD

**Issue by xylar** [conda-forge/esmf-feedstock#59]
https://anaconda.org/conda-forge/esmf/files:

files for esmf-8.1.0.beta.snapshot.33 were meant to go to `esmf_dev` in #56. However, I messed up and didn't include a `channel_sources` section in `conda_build_config.yaml` so they went to main instead.

**Comment by xylar** [comment]
@ocefpaf, I'm documenting this issue here even though I mentioned it here as well: https://github.com/conda-forge/esmpy-feedstock/issues/36

I know you're busy with python 3.9.  When you have some breathing room, it would be good to get all these packages moved to the right label so no one gets confused or is working with a broken environment.

I can report them as broken instead if you prefer but that doesn't quite seem accurate.

**Comment by ocefpaf** [comment]
I think I got them all. Closing this but please reopen if I made a mistake somewhere. Thanks!

**Comment by xylar** [comment]
Thanks so much! Looks good here.  Let me know when you have a chance to do the same on `esmpy`.

**Comment by ocefpaf** [comment]
Done!
