### ISSUE TITLE
Arch migration

### ISSUE THREAD

**Issue by xylar** [conda-forge/esmf-feedstock#74]
For some reason, this feedstock was skipped by both Linux and OSX architecture migration:
https://conda-forge.org/status

We should presumably do the migrations manually

**Comment by xylar** [comment]
Migration would then also need to happen for ESMPy, which is presumably what is actually desired in https://github.com/conda-forge/esmpy-feedstock/pull/53

**Comment by xylar** [comment]
I will try to work on this tomorrow.

**Comment by rljacob** [comment]
Someone should email esmf_support@ucar.edu to get their attention on this.

**Comment by rljacob** [comment]
Try tagging:  @theurich @oehmke

**Comment by theurich** [comment]
Tagging @rsdunlapiv and @rokuingh.

**Comment by rljacob** [comment]
See discussion on https://github.com/conda-forge/esmf-feedstock/pull/75

**Comment by xylar** [comment]
closed via #90
