### ISSUE TITLE
Parallel ESMF builds

### ISSUE THREAD

**Issue by bekozi** [conda-forge/esmf-feedstock#9]
@ocefpaf I noticed the ESMF build is still serial: https://github.com/conda-forge/esmf-feedstock/blob/master/recipe/build.sh#L14. Can we consider transitioning to parallel builds? At least for Linux.

**Comment by ocefpaf** [comment]
I totally missed this. What is the right build flag to fix that? I can add in #8 right now.

**Comment by bekozi** [comment]
``mpich2`` is what we want for Linux: https://github.com/NESII/conda-recipes-nesii/blob/master/esmf/build.sh. ``openmpi`` is the preferred package for ``osx``. However, we have never been able to get ``openmpi`` to work nicely under conda. This may be resolved: https://github.com/conda-forge/esmf-feedstock/issues/4.

**Comment by bekozi** [comment]
Doing some testing: https://github.com/conda-forge/esmf-feedstock/pull/10

**Comment by bekozi** [comment]
See commit message.
